const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const desktopRoot = path.resolve(__dirname, '..')
const read = relativePath => fs.readFileSync(path.join(desktopRoot, relativePath), 'utf8')

test('evaOS Agent package identity and customer artifact contract are exact', () => {
  const pkg = JSON.parse(read('package.json'))
  assert.equal(pkg.productName, 'evaOS Agent')
  assert.equal(pkg.version, '0.2.0-beta.1')
  assert.equal(pkg.build.appId, 'com.electricsheephq.evaos.agent')
  assert.equal(pkg.build.executableName, 'evaOS Agent')
  assert.deepEqual(pkg.build.protocols[0].schemes, ['evaos-agent'])
  assert.equal(pkg.build.artifactName, 'evaOS-Agent-${version}-${arch}.${ext}')
  assert.equal(pkg.build.icon, 'assets/eva')
  assert.equal(pkg.build.afterSign, undefined)
})

test('managed build makes local startup unreachable and consumes auth callbacks in main', () => {
  const main = read('electron/main.cjs')
  const preload = read('electron/preload.cjs')
  const relay = read('electron/eva-ws-relay.cjs')
  const start = main.slice(
    main.indexOf('async function startHermes()'),
    main.indexOf('// Latched-failure short-circuit')
  )
  assert.match(main, /const EVA_MANAGED_BUILD = true/)
  assert.match(start, /if \(EVA_MANAGED_BUILD\)/)
  assert.match(start, /resolveEvaManagedBackend/)
  assert.doesNotMatch(start, /resolveHermesBackend|ensureRuntime|spawn/)
  const managedStart = start.slice(0, start.indexOf('// Latched-failure short-circuit'))
  assert.match(managedStart, /Connecting to your managed evaOS agent/)
  assert.match(managedStart, /evaOS Agent is connected/)
  assert.doesNotMatch(managedStart, /managed Hermes agent|Eva is connected/)
  assert.match(main, /phase: 'eva\.sign-in-required'/)
  const ensureSession = main.slice(
    main.indexOf('async function ensureEvaDesktopSession()'),
    main.indexOf('async function ensureEvaRuntimeEnrollment')
  )
  const explicitSignIn = main.slice(
    main.indexOf('async function signInEvaManagedDesktop()'),
    main.indexOf('async function resetEvaRendererSessions')
  )
  assert.match(ensureSession, /requireEvaDesktopSignIn\(\)/)
  assert.doesNotMatch(ensureSession, /beginEvaDesktopSignIn\(\)/)
  assert.match(explicitSignIn, /beginEvaDesktopSignIn\(\)/)
  assert.match(main, /parsed\.hostname === 'auth'/)
  assert.match(main, /completeEvaDesktopCallback/)
  assert.match(main, /wsUrl: await getEvaWsRelay\(\)\.mintTicket\(\)/)
  assert.match(main, /baseUrl: 'eva-managed:\/\/jackie-david'/)
  assert.match(main, /token: ''/)
  assert.match(main, /error\?\.statusCode === 401 \|\| error\?\.statusCode === 403/)
  assert.match(main, /runtime = await ensureEvaRuntimeEnrollment\(\{ force: true \}\)/)
  assert.match(relay, /buildEvaManagedWsUrl\(upstream\.baseUrl, upstream\.token\)/)
  assert.doesNotMatch(preload, /terminal:|readFileDataUrl|selectPaths|uninstall:|saveImageFromUrl|themes:/)
  assert.match(main, /APP_PROTOCOL = EVA_MANAGED_POLICY\.callbackScheme/)
})

test('managed session persistence encrypts both tokens and restricts the state file', () => {
  const main = read('electron/main.cjs')
  assert.match(main, /token: encryptDesktopSecret\(state\.desktop\.token\)/)
  assert.match(main, /token: encryptDesktopSecret\(state\.runtime\.token\)/)
  assert.match(main, /fs\.chmodSync\(EVA_ENROLLMENT_STATE_PATH, 0o600\)/)
  assert.match(main, /requestEvaManagedApi\(request\)/)
  assert.match(main, /error\?\.statusCode !== 401/)
  assert.match(main, /assertEvaManagedApiRequestAllowed\(request, \{ agentId: runtime\.agentId \}\)/)
  assert.match(main, /assertEvaManagedApiRequestAllowed\(request, \{ agentId: refreshed\.agentId \}\)/)
  assert.match(main, /invalidateEvaAuthWork\(\)/)
  assert.match(main, /resetEvaRendererSessions\(\)/)
})

test('managed member UI exposes one server-bound agent context without profile or integration controls', () => {
  const controller = read('src/app/desktop-controller.tsx')
  const main = read('electron/main.cjs')
  const preload = read('electron/preload.cjs')
  const sidebar = read('src/app/chat/sidebar/index.tsx')
  const statusbar = read('src/app/shell/hooks/use-statusbar-items.tsx')
  const blocked = main.slice(
    main.indexOf('const EVA_BLOCKED_INVOKE_CHANNELS'),
    main.indexOf('function installEvaManagedIpcGuards')
  )

  assert.doesNotMatch(preload, /set: name => ipcRenderer\.invoke\('hermes:profile:set'/)
  assert.match(blocked, /hermes:profile:set/)
  assert.match(sidebar, /item\.id === 'new-session'.*item\.id === 'skills'.*item\.id === 'artifacts'/s)
  assert.match(sidebar, /contentVisible && !managedEva/)
  assert.match(statusbar, /id: 'agents',[\s\S]*?hidden: managedEva/)
  assert.match(statusbar, /id: 'cron',[\s\S]*?hidden: managedEva/)
  assert.match(controller, /managedEva \? \([\s\S]*?<Navigate replace to=\{NEW_CHAT_ROUTE\}/)
  assert.match(controller, /!managedEva && profilesOpen/)
})

test('updater and editable gateway paths fail closed in the managed build', () => {
  const main = read('electron/main.cjs')
  const managed = read('electron/eva-managed.cjs')
  const about = read('src/app/settings/about-settings.tsx')
  const chat = read('src/app/chat/index.tsx')
  const controller = read('src/app/desktop-controller.tsx')
  const gatewayBoot = read('src/app/gateway/hooks/use-gateway-boot.ts')
  const connectingOverlay = read('src/components/gateway-connecting-overlay.tsx')
  const gateway = read('src/app/settings/gateway-settings.tsx')
  const onboarding = read('src/components/onboarding/index.tsx')
  const settings = read('src/app/settings/index.tsx')
  const updates = read('src/store/updates.ts')
  const smoke = read('scripts/test-desktop.mjs')
  assert.match(managed, /Updates are managed by Electric Sheep/)
  assert.match(main, /EVA_BLOCKED_INVOKE_CHANNELS/)
  assert.doesNotMatch(
    main.slice(main.indexOf('const EVA_BLOCKED_INVOKE_CHANNELS'), main.indexOf('function installEvaManagedIpcGuards')),
    /hermes:updates:apply/
  )
  assert.match(main, /gateway settings are managed by Electric Sheep/)
  assert.match(about, /managed-beta · automatic updater disabled/)
  assert.doesNotMatch(about, /NousResearch\/hermes-agent\/releases/)
  assert.match(gatewayBoot, /evaSignInRequired/)
  assert.match(gatewayBoot, /Sign in to evaOS Agent from Settings → Gateway/)
  assert.match(gatewayBoot, /navigate\(`\$\{SETTINGS_ROUTE\}\?tab=gateway`/)
  assert.match(connectingOverlay, /boot\.phase === 'renderer\.enrollment'/)
  assert.match(connectingOverlay, /boot\.phase === 'eva\.sign-in-required'/)
  assert.match(onboarding, /if \(window\.hermesDesktop\?\.eva\)/)
  assert.match(gateway, /Local backends, custom/)
  assert.match(settings, /managedViews/)
  assert.match(chat, /onPickFiles=\{managedEva \? undefined : onPickFiles\}/)
  assert.match(chat, /onTranscribeAudio=\{managedEva \? undefined : onTranscribeAudio\}/)
  assert.match(controller, /const terminalSidebarOpen = !managedEva/)
  assert.match(controller, /const mainOverlays = managedEva \? null/)
  assert.match(updates, /if \(isManagedEva\(\)\)/)
  assert.match(smoke, /evaOS-Agent-/)
  assert.doesNotMatch(smoke, /Hermes\.app|Hermes-\$\{PACKAGE_JSON\.version\}/)
})
